### ISSUE TITLE
[Component] 01 Building License / 02 Garbage Collection Locations

### ISSUE THREAD

**Issue by godspeedhuang** [igorho2000/Taipei-City-Dashboard-FE#11]
> Please submit all issues in English.

> If submitting more than 1 component at once, please number them when filling out the template.

## Please describe the proposed component(s)

1. Building License: The number of approved user and building permits in Taipei by month.
2. Garbage Collection Locations: When and where garbage trucks in Taipei collect trash.

## Datasets to be used

1-1. https://data.taipei/dataset/detail?id=0816f991-e6c8-4da0-a789-d022fee1462b 
1-2. https://data.taipei/dataset/detail?id=d8834353-ff8e-4a6c-9730-a4d3541f2669 
2. https://data.taipei/dataset/detail?id=6bb3304b-4f46-4bb0-8cd1-60c66dcd1cae

## Proposed Chart Types and Map Types

1. TimelineSeparateChart, TimelineStackedChart / N.A
2. BarChart, RadarChart, DistrictChart / Circle

## Additional context

1. Will include history data with this component
2. Will add map filtering to this component

(Fill in "x" to check)

-   [x] I would like to work on this issue myself if approved.

**Comment by igorho2000** [comment]
LGTM!
