### ISSUE TITLE
[Enhancement] Add Component Icons

### ISSUE THREAD

**Issue by Chu-c-git** [igorho2000/Taipei-City-Dashboard-FE#13]
> Please submit all issues in English.

## Type

-   [x] Application Functionalities
-   [ ] New Chart Type
-   [ ] New Map Type
-   [ ] Other

## Please describe your feature request

Add component icons to the application

## Describe alternatives you've considered

No alternatives are present.

## Additional context

N/A

(Fill in "x" to check)

-   [x] I would like to work on this issue myself if approved.

**Comment by igorho2000** [comment]
LTGM!
